apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todo-chatbot.fullname" . }}-secrets
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "todo-chatbot.labels" . | nindent 4 }}
type: Opaque
data:
  GEMINI_API_KEY: {{ .Values.secrets.geminiApiKey | b64enc | quote }}
  SECRET_KEY: {{ .Values.secrets.secretKey | b64enc | quote }}